CREATE DATABASE IF NOT EXISTS webform_db;
USE webform_db;

CREATE TABLE messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NULL,
  telephone VARCHAR(20),
  member_visitor VARCHAR(10),
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);